In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [1]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5956, 9460, 3619, 7931],
 [5956, 9460, 3619, 9253],
 [5956, 2020, 3619, 9789],
 [4387, 663, 5047, 7259, 6010],
 [4387, 663, 5047, 7259, 2916],
 [3383, 5956, 7758, 3619, 8012],
 [1633, 1412, 6024, 7259]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5956 9460 3619 7931]
 [   0    0    0    0 5956 9460 3619 9253]
 [   0    0    0    0 5956 2020 3619 9789]
 [   0    0    0 4387  663 5047 7259 6010]
 [   0    0    0 4387  663 5047 7259 2916]
 [   0    0    0 3383 5956 7758 3619 8012]
 [   0    0    0    0 1633 1412 6024 7259]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step


array([[[ 0.03029386, -0.01585041, -0.03410586, -0.02801811,
         -0.04128126, -0.00344215,  0.00416124, -0.00601189,
         -0.00506435,  0.00725806],
        [ 0.03029386, -0.01585041, -0.03410586, -0.02801811,
         -0.04128126, -0.00344215,  0.00416124, -0.00601189,
         -0.00506435,  0.00725806],
        [ 0.03029386, -0.01585041, -0.03410586, -0.02801811,
         -0.04128126, -0.00344215,  0.00416124, -0.00601189,
         -0.00506435,  0.00725806],
        [ 0.03029386, -0.01585041, -0.03410586, -0.02801811,
         -0.04128126, -0.00344215,  0.00416124, -0.00601189,
         -0.00506435,  0.00725806],
        [-0.03704498, -0.00065647,  0.04264381, -0.00112557,
         -0.02175312, -0.01429372, -0.04786735, -0.01514034,
         -0.01214085, -0.04253783],
        [-0.04190435,  0.02014048,  0.03765888,  0.0166404 ,
         -0.00423016, -0.04186803, -0.03932728, -0.00818933,
         -0.04698067,  0.01849392],
        [ 0.03000918,  0.01876644, -0.01462611, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 5956, 9460, 3619, 7931], dtype=int32)

In [16]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step


array([[ 0.03029386, -0.01585041, -0.03410586, -0.02801811, -0.04128126,
        -0.00344215,  0.00416124, -0.00601189, -0.00506435,  0.00725806],
       [ 0.03029386, -0.01585041, -0.03410586, -0.02801811, -0.04128126,
        -0.00344215,  0.00416124, -0.00601189, -0.00506435,  0.00725806],
       [ 0.03029386, -0.01585041, -0.03410586, -0.02801811, -0.04128126,
        -0.00344215,  0.00416124, -0.00601189, -0.00506435,  0.00725806],
       [ 0.03029386, -0.01585041, -0.03410586, -0.02801811, -0.04128126,
        -0.00344215,  0.00416124, -0.00601189, -0.00506435,  0.00725806],
       [-0.03704498, -0.00065647,  0.04264381, -0.00112557, -0.02175312,
        -0.01429372, -0.04786735, -0.01514034, -0.01214085, -0.04253783],
       [-0.04190435,  0.02014048,  0.03765888,  0.0166404 , -0.00423016,
        -0.04186803, -0.03932728, -0.00818933, -0.04698067,  0.01849392],
       [ 0.03000918,  0.01876644, -0.01462611, -0.03671663,  0.0288507 ,
        -0.01308648,  0.00751877, -0.02743262